### ISSUE TITLE
Cannot Find Premises and Rationales 

### ISSUE THREAD

**Issue by YuxiXie** [jayleicn/VideoLanguageFuturePred#2]
Hi! Thanks for your great work on VLEP.
I find the corresponding premises and rationales quite useful and would like to use them for my own research. Therefore, I am wondering whether you have released the premises and rationales, and if not, will you release them elsewhere in the future? 
Thanks a lot!

**Comment by jayleicn** [comment]
Hi @YuxiXie,

We haven't released premises and rationales yet, but are considering releasing them in the future. However, we don't have a concrete timeline for this.

Best,
Jie

**Comment by YuxiXie** [comment]
I see. Thanks for your answer!
