### ISSUE TITLE
Cannot get the 3D ResNext features of TV clips

### ISSUE THREAD

**Issue by jianjieluo** [jayleicn/VideoLanguageFuturePred#4]
Hi! Thanks for your great work on VLEP.

I find that we can not extract the 3D ResNext motion features of the tv clips since there are no original tv clips in the released vision data. Therefore, I am wondering whether you have released the 3D ResNext features of TV clips, and if not, will you release them elsewhere in the future?

Thanks a lot!

**Comment by jayleicn** [comment]
Hi @jianjieluo,

If you do want ResNext motion features, you can actually concat the frames into a video, though at a much lower frame rate, it may still give a reasonable performance. For 3D features of other types, you can find I3D feature at https://github.com/jayleicn/TVRetrieval, SlowFast features at https://github.com/linjieli222/HERO.

Best,
Jie

**Comment by jianjieluo** [comment]
I see. Thanks for your response!
