### ISSUE TITLE
Can you open source code of the baseline, thank you？

### ISSUE THREAD

**Issue by RQsky** [jayleicn/VideoLanguageFuturePred#6]

**Comment by jayleicn** [comment]
Hi @RQsky,

We don't have plans for releasing the baseline right now. But you can refer to our recent work that has reported results in this dataset: https://github.com/VALUE-Leaderboard/StarterCode. https://github.com/rowanz/merlot is another work in this line. I hope these codebases can help you find the needed resources.

Best,
Jie
