### ISSUE TITLE
Asking for data of "Premise Summary"

### ISSUE THREAD

**Issue by benson1016087** [jayleicn/VideoLanguageFuturePred#7]
Hi,

First, thanks for providing this interesting and challenging dataset. When I read this paper, it says that the dataset contain "Premise Summary", while I didn't see that in data. Can you update that or give a link to download those premise summaries?

Thanks a lot.

**Comment by jayleicn** [comment]
Hi @benson1016087,

Yes, it contains a premise for each example. But we are still deciding whether and how should we distribute this data, since it may give a shortcut to circumvent video+subtitle understanding. We'll let you know if we decide to release it.

Best,
Jie
